model:
  type: resnet50
dataset: imagenet
aug: randaugment
randaug:
  N: 2
  M: 9

cutout: 0
batch: 1024
epoch: 180  # 270
lr: 0.01
lr_schedule:
  type: 'resnet'
  warmup:
    multiplier: 40
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0001
  clip: 0
  lars: False
  label_smoothing: 0.0
