model:
  type: wresnet28_10_brn
dataset: cifar10
aug: randaugment
randaug:
  N: 6
  M: 5    # from appendix
cutout: 16
batch: 256
epoch: 1000
lr: 0.003
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 20
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.00001
